name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Opalstack
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OPALSTACK_HOST }}
          username: ${{ secrets.OPALSTACK_USER }}
          key: ${{ secrets.OPALSTACK_SSH_KEY }}
          source: "_site/*"
          target: ${{ secrets.APP_DIR }}